export const courseData = [
  {
    level: '100 Level',
    courses: [
      {
        id: 'gen-math',
        title: 'General Mathematics I & II',
        desc: 'Foundational calculus, algebra, and trigonometry for engineering applications.',
        img: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=800',
      },
      {
        id: 'gen-phys',
        title: 'General Physics I & II',
        desc: 'Principles of mechanics, waves, optics, and electromagnetism.',
        img: 'https://images.unsplash.com/photo-1532187875605-1ef6c237ddc4?q=80&w=800',
      },
      {
        id: 'gen-chem',
        title: 'General Chemistry I & II',
        desc: 'Covers atomic structure, chemical bonding, states of matter, stoichiometry, and basic thermodynamics.',
        img: 'https://images.unsplash.com/photo-1532187875605-1ef6c237ddc4?q=80&w=800',
      },
      {
        id: 'eng-draw',
        title: 'Engineering Drawing I',
        desc: 'Technical sketching, geometric construction, and introduction to CAD standards.',
        img: 'https://images.unsplash.com/photo-1581094794329-c8112a89af12?q=80&w=800',
      },
      {
        id: 'use-eng',
        title: 'Use of English',
        desc: 'Development of communication skills, including grammar, essay writing, and reading comprehension.',
        img: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=800',
      },
      {
        id: 'phil-logic',
        title: 'Philosophy and Logic',
        desc: 'Introduction to the nature of human thought, reasoning methods, and logical fallacies.',
        img: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?q=80&w=800',
      },
      {
        id: 'nig-cult',
        title: 'Nigerian People and Culture',
        desc: 'Study of Nigerian history, social-political organization, and cultural heritage.',
        img: 'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?q=80&w=800',
      },
      {
        id: 'intro-comp',
        title: 'Introduction to Computer Science',
        desc: 'Basics of computer hardware, software applications, and foundational programming concepts.',
        img: 'https://images.unsplash.com/photo-1517694712202-14dd9538aa97?q=80&w=800',
      },
      {
        id: 'eng-work',
        title: 'Engineering Workshop Practice',
        desc: 'Hands-on skills in metalwork, carpentry, machining, and basic electrical wiring.',
        img: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?q=80&w=800',
      },
    ],
  },
  {
    level: '200 Level',
    courses: [
      {
        id: 'eng-math-ii',
        title: 'Engineering Mathematics I & II',
        desc: 'Advanced calculus, differential equations, and linear algebra tailored for complex system modeling.',
        img: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=800',
      },
      {
        id: 'app-elec',
        title: 'Applied Electricity I & II',
        desc: 'Fundamental analysis of DC/AC circuits, network theorems, and the physical basis of electrical components.',
        img: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?q=80&w=800',
      },
      {
        id: 'elec-dev',
        title: 'Introduction to Electronic Devices',
        desc: 'Physics and operational characteristics of semiconductors, diodes, and transistors in circuit design.',
        img: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800',
      },
      {
        id: 'thermo',
        title: 'Basic Thermodynamics',
        desc: 'Study of energy, heat, work, and the laws governing energy conversion in engineering systems.',
        img: 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?q=80&w=800',
      },
      {
        id: 'fluid-mech',
        title: 'General Fluid Mechanics',
        desc: 'Principles of fluid statics and dynamics, flow measurement, and control in mechanical interfaces.',
        img: 'https://images.unsplash.com/photo-1503694978374-8a2fa686963a?q=80&w=800',
      },
      {
        id: 'mat-sci',
        title: 'Science of Materials',
        desc: 'Microstructure and properties of engineering materials, including conductors, insulators, and semiconductors.',
        img: 'https://images.unsplash.com/photo-1532187875605-1ef6c237ddc4?q=80&w=800',
      },
      {
        id: 'struct-prog',
        title: 'Structured Programming (C/C++)',
        desc: 'Introduction to algorithm development and low-level programming for hardware-software integration.',
        img: 'https://images.unsplash.com/photo-1515879218367-8466d910aaa4?q=80&w=800',
      },
      {
        id: 'eng-mech',
        title: 'Applied Mechanics (Statics & Dynamics)',
        desc: 'Analysis of forces on rigid bodies at rest and in motion, essential for electromechanical systems.',
        img: 'https://images.unsplash.com/photo-1531206715517-5c0ba140b2b8?q=80&w=800',
      },
      {
        id: 'eng-society',
        title: 'The Engineer in Society',
        desc: 'Exploration of professional ethics, the impact of technology on society, and the role of the engineer.',
        img: 'https://images.unsplash.com/photo-1521791136064-7986c2959213?q=80&w=800',
      },
    ],
  },
  {
    level: '300 Level',
    courses: [
      {
        id: 'circ-theory',
        title: 'Electric Circuit Theory I & II',
        desc: 'Advanced analysis of network theorems, transient responses, and Laplace transforms in RLC circuits.',
        img: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?q=80&w=800',
      },
      {
        id: 'elec-machines',
        title: 'Electrical Machines I & II',
        desc: 'Operational principles and performance of DC/AC motors, generators, and transformers.',
        img: 'https://images.unsplash.com/photo-1581092335397-9583ee92d03b?q=80&w=800',
      },
      {
        id: 'analog-elec',
        title: 'Analog Electronic Circuits',
        desc: 'Design and analysis of transistor-based amplifiers, oscillators, and operational amplifier (Op-Amp) applications.',
        img: 'https://images.unsplash.com/photo-1555664424-778a1e5e1b48?q=80&w=800',
      },
      {
        id: 'em-fields',
        title: 'Electromagnetic Fields and Waves',
        desc: 'Study of Maxwell’s equations, electrostatics, magnetostatics, and wave propagation in various media.',
        img: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800',
      },
      {
        id: 'digital-logic',
        title: 'Digital Electronics & Logic Design',
        desc: 'Boolean algebra, combinational and sequential logic circuits, flip-flops, and counters.',
        img: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800',
      },
      {
        id: 'meas-instrum',
        title: 'Measurements and Instrumentation',
        desc: 'Principles of electronic instrumentation, error analysis, and the use of sensors and transducers.',
        img: 'https://images.unsplash.com/photo-1581092162384-8987c1d64718?q=80&w=800',
      },
      {
        id: 'control-theory',
        title: 'Linear Control Systems',
        desc: 'Modeling of physical systems using transfer functions, block diagrams, and stability analysis (Root Locus, Bode plots).',
        img: 'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?q=80&w=800',
      },
      {
        id: 'eng-math-iii',
        title: 'Engineering Mathematics III & IV',
        desc: 'Complex variables, Fourier series, and partial differential equations for solving engineering problems.',
        img: 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?q=80&w=800',
      },
      {
        id: 'num-methods',
        title: 'Numerical Methods',
        desc: 'Algorithmic solutions for mathematical problems that cannot be solved analytically.',
        img: 'https://images.unsplash.com/photo-1509228468518-180dd486490e?q=80&w=800',
      },
    ],
  },
  {
    level: '400 Level',
    courses: [
      {
        id: 'comm-princ',
        title: 'Communication Principles',
        desc: 'Introduction to signal modulation (AM, FM, PM), noise analysis, and the fundamentals of analog and digital communication systems.',
        img: 'https://images.unsplash.com/photo-1551703599-6b3e8379aa81?q=80&w=800',
      },
      {
        id: 'power-systems-i',
        title: 'Electric Power Systems I',
        desc: 'Principles of power generation, transmission line modeling, and distribution network design.',
        img: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?q=80&w=800',
      },
      {
        id: 'micro-proc',
        title: 'Microprocessor Systems & Interfacing',
        desc: 'Architecture, assembly language programming, and hardware interfacing of microprocessors (e.g., 8085/8086 or ARM).',
        img: 'https://images.unsplash.com/photo-1591405351990-4726e33df584?q=80&w=800',
      },
      {
        id: 'em-waves',
        title: 'Electromagnetic Waves & Antennas',
        desc: 'Analysis of Maxwell’s equations for wave propagation, waveguides, and the radiation characteristics of antennas.',
        img: 'https://images.unsplash.com/photo-1563770660941-20978e870e26?q=80&w=800',
      },
      {
        id: 'siwes-it',
        title: 'Students Industrial Work Experience (SIWES)',
        desc: 'A 6-month intensive industrial internship designed to provide practical experience in an engineering firm.',
        img: 'https://images.unsplash.com/photo-1581092160562-40aa08e78837?q=80&w=800',
      },
      {
        id: 'eng-mgmt',
        title: 'Engineering Management & Economics',
        desc: 'Introduction to project management, financial accounting, and economic decision-making for engineering projects.',
        img: 'https://images.unsplash.com/photo-1454165833767-027ffea9e77b?q=80&w=800',
      },
      {
        id: 'control-eng-adv',
        title: 'Advanced Control Engineering',
        desc: 'State-space analysis, digital control systems, and the design of PID controllers for industrial automation.',
        img: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=800',
      },
      {
        id: 'technical-report',
        title: 'Technical Report Writing',
        desc: 'Advanced methods for documenting engineering research, project proposals, and professional presentations.',
        img: 'https://images.unsplash.com/photo-1517842645767-c639042777db?q=80&w=800',
      },
    ],
  },
  {
    level: '500 Level',
    courses: [
      {
        id: 'final-proj',
        title: 'Final Year Research Project',
        desc: 'An independent, supervised technical design or research study involving hardware construction or advanced software simulation.',
        img: 'https://images.unsplash.com/photo-1581092335397-9583ee92d03b?q=80&w=800',
      },
      {
        id: 'dsp',
        title: 'Digital Signal Processing (DSP)',
        desc: 'Theory of discrete-time signals, Z-transforms, digital filter design, and Fast Fourier Transforms (FFT).',
        img: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?q=80&w=800',
      },
      {
        id: 'pwr-elec',
        title: 'Power Electronics & Drives',
        desc: 'Design of converters, inverters, and choppers for controlling high-power industrial motors and renewable energy systems.',
        img: 'https://images.unsplash.com/photo-1517077304055-6e89abbf09b0?q=80&w=800',
      },
      {
        id: 'hv-eng',
        title: 'High Voltage Engineering',
        desc: 'Study of insulation breakdown, lightning protection, and the design of high-voltage transmission equipment.',
        img: 'https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?q=80&w=800',
      },
      {
        id: 'elec-serv-design',
        title: 'Electrical Services Design',
        desc: 'Practical blueprinting of electrical systems for residential, commercial, and industrial buildings using AutoCAD.',
        img: 'https://images.unsplash.com/photo-1503387762-592dea58ef23?q=80&w=800',
      },
      {
        id: 'reliability',
        title: 'Reliability & Maintainability',
        desc: 'Statistical methods for assessing the lifespan and failure rates of electrical components and systems.',
        img: 'https://images.unsplash.com/photo-1581092162384-8987c1d64718?q=80&w=800',
      },
      {
        id: 'comm-eng-adv',
        title: 'Satellite & Mobile Communication',
        desc: 'Advanced study of wireless networks, GSM architecture, and orbital mechanics for satellite links.',
        img: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800',
      },
      {
        id: 'robotics-auto',
        title: 'Robotics & Automation',
        desc: 'Integration of sensors, actuators, and control algorithms to design autonomous robotic systems.',
        img: 'https://images.unsplash.com/photo-1531746790731-6c087fecd05a?q=80&w=800',
      },
      {
        id: 'eng-econ',
        title: 'Engineering Economics & Law',
        desc: 'Contract law, professional ethics, and the financial analysis of large-scale engineering ventures.',
        img: 'https://images.unsplash.com/photo-1454165833767-027ffea9e77b?q=80&w=800',
      },
    ],
  },
];
